Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

@startuml
==create proxy factory(service import)==
-\rsa:importService()
rsa->rsa_rpc_json:createProxy(endpointDescription, celix_rsa_send_request_fp)
rsa_rpc_json->framework:Register remote service proxy factory service\n(celix_service_factory_t)
return factory service id
rsa_rpc_json --> rsa:proxyId

==use proxy(remote service call)==
framework/-:remote service call
framework->rsa_rpc_json:get remote service proxy service(use celix_service_factory_t)
alt proxy service is not existed
rsa_rpc_json->rsa_rpc_json:Create proxy service according to the interface description file
end
rsa_rpc_json-->framework:proxy service
framework->rsa_rpc_json:call proxy service
rsa_rpc_json->rsa_rpc_json:serialize invocation information of proxy service
rsa_rpc_json-->rsa:serialized result (send by celix_rsa_send_request_fp)
@enduml