Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

@startuml
component ShellTUI as "Celix Shell TUI\n(textual user interface)"
component ShellWUI as "Celix Shell WUI\n(web user interface)"
component ShellCommandA as "Shell Command A"
component ShellCommandB as "Shell Command B"
component ShellCommandC as "Shell Command C"
component CelixShell as "Celix Shell"
() Shell as "celix_shell_t"
() ShellCommandService as "celix_shell_command_t"

ShellTUI -down-( Shell
ShellWUI -down-( Shell

CelixShell -up- Shell
CelixShell  -down-( ShellCommandService

ShellCommandA -up- ShellCommandService
ShellCommandB -up- ShellCommandService
ShellCommandC -up- ShellCommandService

@enduml

