= PubSub Serialization

WARNING: The PubSub Serialization Services are still work in progress. The current PubSubAdmins still work differently.

PubSub serialization is realized by providing a single marker serialization service
(`pubsub_message_serialization_marker_t`) and multiple message serialization services
(`pubsub_message_serialization_service_t`), a message serialization service per msg type.

Both the serialization marker service and message serialization services must provide a mandatory `serialization.type`.
This is used to identify the serialization "type" they belong to, for example "json" or "avrobin".

The serialization services are used by the PubSub Admins to send (serialize) and receive (deserialize) messages.
The PubSub Admins arrange the transport for the message the the serialization services the serializations.


pubsub_message_serialization_marker_t
[source,c]
----
#define PUBSUB_MESSAGE_SERIALIZATION_MARKER_NAME      "pubsub_serialization_marker"
#define PUBSUB_MESSAGE_SERIALIZATION_MARKER_VERSION   "1.0.0"
#define PUBSUB_MESSAGE_SERIALIZATION_MARKER_RANGE     "[1,2)"

#define PUBSUB_MESSAGE_SERIALIZATION_MARKER_SERIALIZATION_TYPE_PROPERTY     "serialization.type"

/**
 * Marker which should be registered to mark the presence of this type of
 * serialization service for the different message types.
 *
 * Mandatory property is PUBSUB_SERIALIZATION_MARKER_SERIALIZATION_TYPE_PROPERTY (e.g. json)
 */
typedef struct pubsub_message_serialization_marker {
    void *handle;
} pubsub_message_serialization_marker_t;
----

pubsub_message_serialization_service_t
[source,c]
----
#define PUBSUB_MESSAGE_SERIALIZATION_SERVICE_NAME      "pubsub_message_serialization_service"
#define PUBSUB_MESSAGE_SERIALIZATION_SERVICE_VERSION   "1.0.0"
#define PUBSUB_MESSAGE_SERIALIZATION_SERVICE_RANGE     "[1,2)"

#define PUBSUB_MESSAGE_SERIALIZATION_SERVICE_SERIALIZATION_TYPE_PROPERTY     "serialization.type"
#define PUBSUB_MESSAGE_SERIALIZATION_SERVICE_MSG_FQN_PROPERTY                "msg.fqn"
#define PUBSUB_MESSAGE_SERIALIZATION_SERVICE_MSG_VERSION_PROPERTY            "msg.version"
#define PUBSUB_MESSAGE_SERIALIZATION_SERVICE_MSG_ID_PROPERTY                 "msg.id"

/**
 * A message serialization service for a serialization type (e.g. json) and
 * for a specific msg type (based on the fully qualified name) and version.
 *
 * The properties serialization.type, msg,fqn, msg.version and msg.id are mandatory
 */
typedef struct pubsub_message_serialization_service {
    void* handle;

    celix_status_t (*serialize)(void* handle, const void* input, struct iovec** output, size_t* outputIovLen);
    void (*freeSerializedMsg)(void* handle, struct iovec* input, size_t inputIovLen);
    celix_status_t (*deserialize)

(void* handle, const struct iovec* input, size_t inputIovLen, void** out); //note inputLen can be 0 if predefined size is not needed
    void (*freeDeserializedMsg)(void* handle, void* msg);

} pubsub_message_serialization_service_t;
----

== PubSub Serialization Matching

TODO: Explain matching and usage service ranking on serialization marker service.


=== Match Serializer for Subscriber
[plantuml]
----
@startuml
actor PubSubUser

PubSubUser -> BundleContext: Register Subscriber Service
BundleContext -> Framework: Register Subscriber Service
Framework -> PubSubTopologyManager : Service Added (service tracker)
PubSubTopologyManager --> Framework
Framework --> BundleContext
BundleContext --> PubSubUser

== PubSubAdmin Setup ==

loop psa handling thread
PubSubTopologyManager -> PubSubTopologyManager: pstm_setupTopicReceivers
activate PubSubTopologyManager
PubSubTopologyManager ->  PubSubAdmin: matchSubscriber
PubSubAdmin -> PubSubUtils: matchSerializer
PubSubUtils --> PubSubAdmin
PubSubAdmin --> PubSubTopologyManager
PubSubTopologyManager -> PubSubAdmin: setupTopicReceiver
PubSubAdmin -> PubSubAdmin: create topic receiver
PubSubAdmin --> PubSubTopologyManager
deactivate PubSubTopologyManager
end

@enduml
----

=== Match Serializer for Publisher
[plantuml]
----
@startuml
actor PubSubUser

PubSubUser -> BundleContext: Request Publisher Service
BundleContext -> Framework: Register Service Listener hook
Framework -> PubSubTopologyManager : Listener Added
PubSubTopologyManager --> Framework
Framework --> BundleContext
BundleContext --> PubSubUser

== PubSubAdmin Setup ==

loop psa handling thread
PubSubTopologyManager -> PubSubTopologyManager: pstm_setupTopicSenders
activate PubSubTopologyManager
PubSubTopologyManager ->  PubSubAdmin: matchPublisher
PubSubAdmin -> PubSubUtils: matchSerializer
PubSubUtils --> PubSubAdmin
PubSubAdmin --> PubSubTopologyManager
PubSubTopologyManager -> PubSubAdmin: setupTopicSender
PubSubAdmin -> PubSubAdmin: create topic sender
PubSubAdmin -> BundleContext: Register Publisher Service
BundleContext -> PubSubUser: Publisher Added
PubSubUser --> BundleContext
BundleContext --> PubSubAdmin
PubSubAdmin --> PubSubTopologyManager
deactivate PubSubTopologyManager
end

@enduml
----

== PubSub Serialization Provider
The PubSub Serialization Provider (`pubsub_serialization_provider_t`) is a helper object which can be used to more easily
create serialization services based on descriptors (libdfi). It arranges tracking bundles, reading descriptor files,
generating errors for invalid descriptors and provides a shell command to interactively query the available descriptors.

The PubSub Serialization Provider needs to be constructor with the serializations service functions
(`serialize`, `freeSerializedMsg`, `deserialize` and `freeDeserializedMsg`)

The PubSub Serialization Provider is part of the `Celix::pubsub_utils` static library.

[ditaa]
----
             +----------------+
             | PubSub User    |
             | (bundle)       |              +----------------+
             |                |  contains    |                |
             |                +------------->+  +-------------+--+
             |                |              |  |                |
             +-------^--------+              |  | +--------------+--+
                     |                       |  | | examples.Types  |
                     |       +-------------->+  | | (descriptor)    |
             tracks  |       |    reads      +----+                 |
             bundles |       |                  | |                 |
                     |       |                  +-+                 |
                     |       |                    |                 |
                     |       |                    |             {d} |
                     |       |                    +-----------------+
                     |       |
                     |       |
                     |       |
           +---------+-------+-+
           |  JSON             |
           |  Serialization    |             +----------------+
           |  Provider         +------------>+                |
           |  (bundle)         |  provides   |  +----------------+
           |                   |             |  |             |  |
           |                   |             |  | +-----------+--+--+
           |                   |             |  | |                 |  Properties:
           |                   |             |  | |  PubSub         |  serialization.type=json
           +--+--------------+-+             +----+  Message        |  msg.fqn=examples.Type
              |              |                  | |  Serialization  |  msg.version=...
              |              |                  +-+  Service        |  msg.id=...
              |              |                    |  (service)      |
    specialize|              |                    |                 |
              |              |                    +-----------------+
              |              |
              |              |
              v              |               +------------------+
+-------------+-----+        |               |                  |  Properties:
|                   |        |               | PubSub           |  serialization.type=json
|  PubSub           |        |               | Message          |
|  Serialization    |        +-------------->+ Serialization    |
|  Provider         |           provides     | Marker           |
|  (library)        |                        | (service)        |
|                   |                        |                  |
|                   |                        +------------------+
+-------------------+
----

== PubSub Serialization Handler
WARINING: TODO
