name: Standalone Celix etcdlib Weekly

on:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        compiler: [gcc]
    timeout-minutes: 15
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq --no-install-recommends \
            build-essential \
            cmake \
            curl \
            libjansson-dev \
            libcurl4-openssl-dev
      - name: Build
        env:
          CC: ${{ matrix.compiler }}
          CXX: ${{ matrix.cxx_compiler }}
        run: |
          mkdir build install
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../install ../libs/etcdlib
          make -j && make install
