name: Standalone Celix etcdlib

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.3.0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq --no-install-recommends \
            build-essential \
            cmake \
            curl \
            libjansson-dev \
            libcurl4-openssl-dev
      - name: Build
        run: |
          mkdir build install
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../install ../libs/etcdlib
          make -j $(nproc) && make install
